#! /bin/sh

CFLAGS="-O -Winline -Wall -Wshadow -fomit-frame-pointer -g"

gcc $CFLAGS -c vg_cachesim.c
/usr/bin/gcc -shared vg_cachesim.o -o vgskin_cachesim.so

cp vgskin_cachesim.so lib/valgrind

cp vgskin_cachesim.usage lib/valgrind

