#! /bin/sh

CFLAGS="-O -Winline -Wall -Wshadow -fomit-frame-pointer -g"

gcc $CFLAGS -c vg_lackey2.c
gcc $CFLAGS -c vg_instrument.c
/usr/bin/gcc -shared \
    vg_lackey2.o \
    vg_instrument.o \
    -o vgskin_lackey2.so

cp vgskin_lackey2.so lib/valgrind



