#! /bin/sh

CFLAGS="-O -Winline -Wall -Wshadow -fomit-frame-pointer -g"

gcc $CFLAGS -c vg_lackey.c
gcc $CFLAGS -c vg_instrument.c
/usr/bin/gcc -shared \
    vg_lackey.o \
    vg_instrument.o \
    -o vgskin_lackey.so

cp vgskin_lackey.so lib/valgrind



