Use of uninitialised value of size 4
   at 0x........: main (origin-jump.c:13)
 Uninitialised value has possible origin 1
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (origin-jump.c:9)

Jump to the invalid address stated on the next line
   at 0x........: ???
   by 0x........: (below main) (in /...libc...)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Process terminating with default action of signal 11 (SIGSEGV)
 Access not within mapped region at address 0x........
   at 0x........: ???
   by 0x........: (below main) (in /...libc...)
