
Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:44)
 Address 0x........ is 1 bytes inside a block of size 3 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (varinfo1.c:42)

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:47)
 Location 0x........ is 0 bytes inside global var "global_u1"
 declared at varinfo1.c:30

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:48)
 Location 0x........ is 0 bytes inside global var "global_i1"
 declared at varinfo1.c:32

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:49)
 Location 0x........ is 0 bytes inside global_u2[3],
 a global variable declared at varinfo1.c:34

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:50)
 Location 0x........ is 0 bytes inside global_i2[7],
 a global variable declared at varinfo1.c:36

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo1.c:25)
   by 0x........: main (varinfo1.c:51)
 Location 0x........ is 0 bytes inside local var "local"
 declared at varinfo1.c:41, in frame #1 of thread 1

ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 1 allocs, 1 frees, 3 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
