
Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo2.c:25)
   by 0x........: foo (varinfo2.c:36)
   by 0x........: main (varinfo2.c:46)
 Location 0x........ is 0 bytes inside var[7],
 declared at varinfo2.c:34, in frame #1 of thread 1

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo2.c:25)
   by 0x........: foo (varinfo2.c:38)
   by 0x........: main (varinfo2.c:46)
 Location 0x........ is 2 bytes inside var.bar,
 declared at varinfo2.c:37, in frame #1 of thread 1

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo2.c:25)
   by 0x........: foo (varinfo2.c:41)
   by 0x........: main (varinfo2.c:46)
 Location 0x........ is 1 byte inside local var "var"
 declared at varinfo2.c:32, in frame #1 of thread 1

ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 0 allocs, 0 frees, 0 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
