
Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo4.c:25)
   by 0x........: blah (varinfo4.c:42)
   by 0x........: main (varinfo4.c:51)
 Location 0x........ is 1 byte inside a[3].xyzzy[21].c1,
 declared at varinfo4.c:40, in frame #1 of thread 1

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo4.c:25)
   by 0x........: blah (varinfo4.c:43)
   by 0x........: main (varinfo4.c:51)
 Location 0x........ is 0 bytes inside a[5].bong,
 declared at varinfo4.c:40, in frame #1 of thread 1

Uninitialised byte(s) found during client check request
   at 0x........: croak (varinfo4.c:25)
   by 0x........: blah (varinfo4.c:44)
   by 0x........: main (varinfo4.c:51)
 Location 0x........ is 1 byte inside a[3].xyzzy[21].c2[2],
 declared at varinfo4.c:40, in frame #1 of thread 1

ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 0 allocs, 0 frees, 0 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
