#!/bin/bash

downloads="$HOME/software/downloads"

if [ ! -e /usr/include/tiffio.h ]; then
  echo "Error: could not find file tiffio.h. Please install libtiff4-dev."
  exit 1
fi

export LC_ALL=C

mkdir -p "${downloads}"

cd "$(dirname $0)/.."

if [ -e splash2 ]; then
  echo "Error: a directory with the name splash2 already exists. Please"
  echo "remove it before running this script, or run this script in another"
  echo "directory."
  exit 1
fi

(
  cd "$downloads"
  if [ ! -e splash2.tar.gz ]; then
    wget -q http://www-flash.stanford.edu/apps/SPLASH/splash2.tar.gz
  fi
)

tar zxf $downloads/splash2.tar.gz
cd splash2
patch -p1 -s < ../scripts/splash2.patch

for m in $(find codes -name Makefile)
do
  echo "==== $m ===="
  make -s -C $(dirname $m)
done
