#! /bin/sh
#----------------------------------------------------------------------------
# Filter results of a Valgrind run so that all things that can vary between
# differently compiled versions are removed: process ids, addresses, line
# numbers, paths.
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
# Multi-stage pipe
#----------------------------------------------------------------------------
# Skip first four lines (valgrind intro)  
# XXX: be more clever/subtle; eg. if there's just a 1-line error message
# don't cut it
tail +5                                                                 | 

# Remove ==pid== and --pid-- and ++pid++ strings 
sed "s/\(==\|--\|++\)[0-9]\{3,5\}\1 //"                                 | 

# Anonymise addresses
sed "s/0x[0-9A-Fa-f]\+/0x......../"                                     |

# Anonymise line numbers in vg_clientfuncs.c
sed "s/vg_clientfuncs.c:[0-9]\+/vg_clientfuncs.c:.../"                  |

# Anonymise paths like "({in,within} /local/foo/bar/tests/memcheck/badjump)"
sed "s/(\(in\|within\) \/.*\/tests\/\(.*\))$/(\1 \/...\/tests\/\2)/"    |

# Anonymise paths like "(in /foo/bar/libc-baz.so)"
sed "s/(in \/.*libc.*)$/(in \/...libc...)/"                             |

# Anonymise paths like "__libc_start_main (../foo/bar/libc-quux.c:129)"
sed "s/__libc_\(.*\) (.*)$/__libc_\1 (...libc...)/"

