#! /bin/sh

# This filter should be applied to *every* stderr results.  It removes Valgrind
# startup stuff and pid numbers.

# Skip first four lines (valgrind intro)  
# XXX: be more clever/subtle; eg. if there's just a 1-line error message
# don't cut it
tail +5                                                                 | 

# Remove ==pid== and --pid-- and ++pid++ strings 
sed "s/\(==\|--\|++\)[0-9]\{3,5\}\1 //"

