#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                    |

# Anonymise addresses
$dir/../../tests/filter_addresses                       |

# Remove "Thrcheck, ..." line and the following copyright line.
sed "/^Thrcheck, a thread error detector/ , /./ d" |

# Anonymise line numbers in tc_intercepts.c
sed "s/tc_intercepts.c:[0-9]*/tc_intercepts.c:.../"  |

# Change (eg) "/lib64/libpthread-2.5.so" into "/lib/libpthread..."
sed "s/lib64/lib/g" | 
sed "s/libpthread.*so/libpthread\.\.\./g" |

$dir/../../tests/filter_test_paths
