
Thread #3 was created
   at 0x........: clone (in /...libc...)
   by 0x........: ...
   by 0x........: pthread_create@@GLIBC_2.2.5 (in /lib/libpthread...)
   by 0x........: pthread_create@* (tc_intercepts.c:...)
   by 0x........: main (hg02_deadlock.c:36)

Thread #3: Lock acquisition order is inconsistent with previously observed ordering
   at 0x........: pthread_mutex_lock (tc_intercepts.c:...)
   by 0x........: t2 (hg02_deadlock.c:20)
   by 0x........: mythread_wrapper (tc_intercepts.c:...)
   by 0x........: ...
   by 0x........: ...

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
