
Thread #1 is the program's root thread

Thread #1 unlocked a not-locked lock at 0x........ 
   at 0x........: pthread_rwlock_unlock (tc_intercepts.c:...)
   by 0x........: main (tc12_rwl_trivial.c:24)
  Lock at 0x........ was first observed
   at 0x........: pthread_rwlock_init (tc_intercepts.c:...)
   by 0x........: main (tc12_rwl_trivial.c:13)

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
