
Thread #6 was created
   at 0x........: clone (in /...libc...)
   by 0x........: ...
   by 0x........: pthread_create@@GLIBC_2.2.5 (in /lib/libpthread...)
   by 0x........: pthread_create@* (tc_intercepts.c:...)
   by 0x........: main (tc14_laog_dinphils.c:34)

Thread #6: Lock acquisition order is inconsistent with previously observed ordering
   at 0x........: pthread_mutex_lock (tc_intercepts.c:...)
   by 0x........: dine (tc14_laog_dinphils.c:19)
   by 0x........: mythread_wrapper (tc_intercepts.c:...)
   by 0x........: ...
   by 0x........: ...

ERROR SUMMARY: 1000 errors from 1 contexts (suppressed: 0 from 0)
