
Establish order 1 -> 2
Try order 2 -> 1.  This gives an error.
Thread #1 is the program's root thread

Thread #1: Lock acquisition order is inconsistent with previously observed ordering
   at 0x........: pthread_mutex_lock (tc_intercepts.c:...)
   by 0x........: main (tc15_laog_lockdel.c:36)
Free 2 and re-allocate it.  This gives it a new identity,
so a second locking sequence 2 -> 1 should now be OK.
done

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
