
Invalid read of size 8
   at 0x........: main (fp.c:13)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, the 8-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:11)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid write of size 8
   at 0x........: main (fp.c:13)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, the 8-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:11)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid read of size 4
   at 0x........: main (fp.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, the 4-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid write of size 4
   at 0x........: main (fp.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, the 4-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
