
Invalid read of size 4
   at 0x........: main (hp_bounds.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes after the accessing pointer's
 legitimate range, the 400-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (hp_bounds.c:6)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid read of size 4
   at 0x........: main (hp_bounds.c:10)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, the 400-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (hp_bounds.c:6)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
