
Invalid read of size 1
   at 0x........: main (pth_specific.c:19)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, the 100-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (pth_specific.c:17)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid read of size 1
   at 0x........: main (pth_specific.c:27)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, the 100-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (pth_specific.c:17)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
