
Invalid read of size 1
   at 0x........: main (unaligned.c:33)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, the 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (unaligned.c:8)
   by 0x........: __libc_start_main (...libc...)

Invalid read of size 1
   at 0x........: main (unaligned.c:37)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, the 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (unaligned.c:8)
   by 0x........: __libc_start_main (...libc...)

Invalid read of size 1
   at 0x........: main (unaligned.c:39)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes after the accessing pointer's
 legitimate range, the 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (unaligned.c:8)
   by 0x........: __libc_start_main (...libc...)

Invalid read of size 1
   at 0x........: main (unaligned.c:43)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes after the accessing pointer's
 legitimate range, the 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (unaligned.c:8)
   by 0x........: __libc_start_main (...libc...)

ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
