

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 100000 bytes in 1000 blocks.
malloc/free: 1000 allocs, 0 frees, 100000 bytes allocated.
For counts of detected errors, rerun with: -v
searching for pointers to 1000 not-freed blocks.
checked ... bytes.

definitely lost: 99900 bytes in 999 blocks.
possibly lost:   100 bytes in 1 blocks.
still reachable: 0 bytes in 0 blocks.

100 bytes in 1 blocks are possibly lost in loss record 1 of 2
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: test (trivialleak.c:8)
   by 0x........: main (trivialleak.c:13)
   by 0x........: __libc_start_main (...libc...)

99900 bytes in 999 blocks are definitely lost in loss record 2 of 2
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: test (trivialleak.c:8)
   by 0x........: main (trivialleak.c:13)
   by 0x........: __libc_start_main (...libc...)

LEAK SUMMARY:
   definitely lost: 99900 bytes in 999 blocks.
   possibly lost:   100 bytes in 1 blocks.
   still reachable: 0 bytes in 0 blocks.
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --show-reachable=yes

