
Command line
   ./peak
Startup, with flags:
   --command-line-only=yes
   --memcheck:leak-check=no
   --tool=massif
   --stacks=no
   --time-unit=B
   -v
   -v
   --peak-inaccuracy=1000
Contents of /proc/version:
  Linux version 2.6.15-1.1833_FC4 (bhcompile@hs20-bc1-1.build.redhat.com) (gcc version 4.0.2 20051125 (Red Hat 4.0.2-8)) #1 Wed Mar 1 23:41:37 EST 2006
Arch and hwcaps: X86, x86-sse1-sse2
Page sizes: currently 4096, max supported 4096
Valgrind library directory: /home/njn/grind/massif3/.in_place
Massif: alloc-fns:
Massif:   0: malloc
Massif:   1: __builtin_new
Massif:   2: operator new(unsigned)
Massif:   3: operator new(unsigned long)
Massif:   4: __builtin_vec_new
Massif:   5: operator new[](unsigned)
Massif:   6: operator new[](unsigned long)
Massif:   7: calloc
Massif:   8: realloc
Massif:   9: memalign
Massif:   10: operator new(unsigned, std::nothrow_t const&)
Massif:   11: operator new[](unsigned, std::nothrow_t const&)
Massif:   12: operator new(unsigned long, std::nothrow_t const&)
Massif:   13: operator new[](unsigned long, std::nothrow_t const&)
TT/TC: VG_(init_tt_tc) (startup of code management)
TT/TC: cache: 8 sectors of 9644544 bytes each = 77156352 total
TT/TC: table: 524168 total entries, max occupancy 419328 (80%)
Reading syms from /lib/ld-2.3.5.so (0x23C000)
   svma 0x000023C000, avma 0x000023C000
summarise_context(loc_start = 0x5D): cannot summarise(why=1):   
0x66: 44(r3) u  u  u  c-36 u  u  c-44 c-40 c-4 u  u  u  u  u  u  u  u  u  u  u  
summarise_context(loc_start = 0x66): cannot summarise(why=1):   
0x69: 44(r3) u  u  u  c-36 u  u  u  c-40 c-4 u  u  u  u  u  u  u  u  u  u  u  
summarise_context(loc_start = 0x69): cannot summarise(why=1):   
0x78: 44(r3) u  u  u  c-36 u  u  u  u  c-4 u  u  u  u  u  u  u  u  u  u  u  
Reading syms from /home/njn/grind/massif3/massif/tests/peak (0x8048000)
   svma 0x0008048000, avma 0x0008048000
Reading syms from /home/njn/grind/massif3/massif/massif-x86-linux (0x38000000)
   svma 0x0038000000, avma 0x0038000000
   object doesn't have a dynamic symbol table
Massif: startup S.  0 (t:0, hp:0, ad:0, st:0)
TT/TC: initialise sector 0
Reading syms from /home/njn/grind/massif3/coregrind/vgpreload_core-x86-linux.so (0x4001000)
   svma 0x0000000000, avma 0x0004001000
Reading syms from /home/njn/grind/massif3/massif/vgpreload_massif-x86-linux.so (0x4003000)
   svma 0x0000000000, avma 0x0004003000
Reading syms from /lib/libc-2.3.5.so (0x25A000)
   svma 0x000025A000, avma 0x000025A000
summarise_context(loc_start = 0x34): cannot summarise(why=1):   
0x4d: 0(r0) u  c60 c56 c52 u  c44 c40 c36 c-4 u  u  u  u  u  u  u  u  u  u  u  
REDIR: 0x2bf41e (malloc) redirected to 0x4003e13 (malloc)
Massif:   alloc S.  1 (t:108, hp:100, ad:8, st:0)
Massif:   alloc S.  2 (t:117, hp:101, ad:16, st:0)
REDIR: 0x2bd5e8 (free) redirected to 0x40049a4 (free)
Massif: de-PEAK Sp  3 (t:117, hp:101, ad:16, st:0)
Massif: dealloc S.  4 (t:126, hp:100, ad:8, st:0)
Massif:   alloc S.  5 (t:234, hp:200, ad:16, st:0)
Massif:   alloc S.  6 (t:243, hp:201, ad:24, st:0)
Massif: de-PEAK Sp  7 (t:243, hp:201, ad:24, st:0)
Massif: dealloc S.  8 (t:252, hp:200, ad:16, st:0)
Massif:   alloc S.  9 (t:360, hp:300, ad:24, st:0)
Massif:   alloc S. 10 (t:369, hp:301, ad:32, st:0)
Massif: de-PEAK Sp 11 (t:369, hp:301, ad:32, st:0)
Massif: dealloc S. 12 (t:378, hp:300, ad:24, st:0)
Massif:   alloc S. 13 (t:486, hp:400, ad:32, st:0)
Massif:   alloc S. 14 (t:495, hp:401, ad:40, st:0)
Massif: de-PEAK Sp 15 (t:495, hp:401, ad:40, st:0)
Massif: dealloc S. 16 (t:504, hp:400, ad:32, st:0)
Massif:   alloc S. 17 (t:612, hp:500, ad:40, st:0)
Massif:   alloc S. 18 (t:621, hp:501, ad:48, st:0)
Massif: de-PEAK Sp 19 (t:621, hp:501, ad:48, st:0)
Massif: dealloc S. 20 (t:630, hp:500, ad:40, st:0)
Massif:   alloc S. 21 (t:738, hp:600, ad:48, st:0)
Massif:   alloc S. 22 (t:747, hp:601, ad:56, st:0)
Massif: de-PEAK Sp 23 (t:747, hp:601, ad:56, st:0)
Massif: dealloc S. 24 (t:756, hp:600, ad:48, st:0)
Massif:   alloc S. 25 (t:864, hp:700, ad:56, st:0)
Massif:   alloc S. 26 (t:873, hp:701, ad:64, st:0)
Massif: de-PEAK Sp 27 (t:873, hp:701, ad:64, st:0)
Massif: dealloc S. 28 (t:882, hp:700, ad:56, st:0)
Massif:   alloc S. 29 (t:990, hp:800, ad:64, st:0)
Massif:   alloc S. 30 (t:999, hp:801, ad:72, st:0)
Massif: de-PEAK Sp 31 (t:999, hp:801, ad:72, st:0)
Massif: dealloc S. 32 (t:1008, hp:800, ad:64, st:0)
Massif:   alloc S. 33 (t:1116, hp:900, ad:72, st:0)
Massif:   alloc S. 34 (t:1125, hp:901, ad:80, st:0)
Massif: de-PEAK Sp 35 (t:1125, hp:901, ad:80, st:0)
Massif: dealloc S. 36 (t:1134, hp:900, ad:72, st:0)
Massif:   alloc S. 37 (t:1242, hp:1000, ad:80, st:0)
Massif:   alloc S. 38 (t:1251, hp:1001, ad:88, st:0)
Massif: de-PEAK Sp 39 (t:1251, hp:1001, ad:88, st:0)
Massif: dealloc S. 40 (t:1260, hp:1000, ad:80, st:0)
Massif:   alloc S. 41 (t:1368, hp:1100, ad:88, st:0)
Massif:   alloc S. 42 (t:1377, hp:1101, ad:96, st:0)
Massif: dealloc S. 43 (t:1386, hp:1100, ad:88, st:0)
Massif:   alloc S. 44 (t:1494, hp:1200, ad:96, st:0)
Massif:   alloc S. 45 (t:1503, hp:1201, ad:104, st:0)
Massif: de-PEAK Sp 46 (t:1503, hp:1201, ad:104, st:0)
Massif: dealloc S. 47 (t:1512, hp:1200, ad:96, st:0)
Massif:   alloc S. 48 (t:1620, hp:1300, ad:104, st:0)
Massif:   alloc S. 49 (t:1629, hp:1301, ad:112, st:0)
Massif: dealloc S. 50 (t:1638, hp:1300, ad:104, st:0)
Massif:   alloc S. 51 (t:1746, hp:1400, ad:112, st:0)
Massif:   alloc S. 52 (t:1755, hp:1401, ad:120, st:0)
Massif: de-PEAK Sp 53 (t:1755, hp:1401, ad:120, st:0)
Massif: dealloc S. 54 (t:1764, hp:1400, ad:112, st:0)
Massif:   alloc S. 55 (t:1872, hp:1500, ad:120, st:0)
Massif:   alloc S. 56 (t:1881, hp:1501, ad:128, st:0)
Massif: dealloc S. 57 (t:1890, hp:1500, ad:120, st:0)
Massif:   alloc S. 58 (t:1998, hp:1600, ad:128, st:0)
Massif:   alloc S. 59 (t:2007, hp:1601, ad:136, st:0)
Massif: de-PEAK Sp 60 (t:2007, hp:1601, ad:136, st:0)
Massif: dealloc S. 61 (t:2016, hp:1600, ad:128, st:0)
Massif:   alloc S. 62 (t:2124, hp:1700, ad:136, st:0)
Massif:   alloc S. 63 (t:2133, hp:1701, ad:144, st:0)
Massif: dealloc S. 64 (t:2142, hp:1700, ad:136, st:0)
Massif:   alloc S. 65 (t:2250, hp:1800, ad:144, st:0)
Massif:   alloc S. 66 (t:2259, hp:1801, ad:152, st:0)
Massif: de-PEAK Sp 67 (t:2259, hp:1801, ad:152, st:0)
Massif: dealloc S. 68 (t:2268, hp:1800, ad:144, st:0)
Massif:   alloc S. 69 (t:2376, hp:1900, ad:152, st:0)
Massif:   alloc S. 70 (t:2385, hp:1901, ad:160, st:0)
Massif: dealloc S. 71 (t:2394, hp:1900, ad:152, st:0)
Massif:   alloc S. 72 (t:2502, hp:2000, ad:160, st:0)
Massif:   alloc S. 73 (t:2511, hp:2001, ad:168, st:0)
Massif: de-PEAK Sp 74 (t:2511, hp:2001, ad:168, st:0)
Massif: dealloc S. 75 (t:2520, hp:2000, ad:160, st:0)
Caught __NR_exit; running __libc_freeres()

Massif: heap allocs:          40
Massif: heap reallocs:        0
Massif: heap frees:           20
Massif: stack allocs:         0
Massif: stack frees:          0
Massif: XPts:                 7
Massif: top-XPts:             2 (28%)
Massif: XPt-init-expansions:  5
Massif: XPt-later-expansions: 0
Massif: SXPt allocs:          77
Massif: SXPt frees:           0
Massif: skipped snapshots:    0
Massif: real snapshots:       76
Massif: detailed snapshots:   15
Massif: peak snapshots:       15
Massif: cullings:             0
Massif: XCon_redos:           0
translate:            fast SP updates identified: 0 (   --%)
translate:   generic_known SP updates identified: 0 (   --%)
translate: generic_unknown SP updates identified: 0 (   --%)
    tt/tc: 2,987 tt lookups requiring 2,996 probes
    tt/tc: 2,987 fast-cache updates, 2 flushes
 transtab: new        1,489 (32,900 -> 182,505; ratio 55:10) [0 scs]
 transtab: dumped     0 (0 -> ??)
 transtab: discarded  0 (0 -> ??)
scheduler: 21,885 jumps (bb entries).
scheduler: 0/1,610 major/minor sched events.
   sanity: 1 cheap, 1 expensive checks.
   exectx: 30,011 lists, 0 contexts (avg 0 per list)
   exectx: 0 searches, 0 full compares (0 per 1000)
   exectx: 0 cmp2, 0 cmp4, 0 cmpAll
 errormgr: 0 supplist searches, 0 comparisons during search
 errormgr: 0 errlist searches, 0 comparisons during search

------ Valgrind's internal memory use stats follow ------
core    :  1 sbs,     3 bs,  1/1  free bs, 1048576 mmap,   65552 loan
tool    :  1 sbs,   161 bs,  2/2  free bs, 1048576 mmap,  325904 loan
symtab  :  3 sbs,   199 bs,  7/7  free bs, 3145728 mmap, 1949288 loan
client  :  1 sbs,    21 bs,  1/1  free bs, 1048576 mmap,    2080 loan
demangle:  0 sbs,     0 bs,  0/0  free bs,       0 mmap,       0 loan
exectxt :  0 sbs,     0 bs,  0/0  free bs,       0 mmap,       0 loan
errors  :  0 sbs,     0 bs,  0/0  free bs,       0 mmap,       0 loan
ttaux   :  1 sbs,    75 bs, 13/13 free bs,   65536 mmap,    4624 loan
------
core    :  1048576 mmap'd,    65552/   65552 max/curr
tool    :  1048576 mmap'd,   325920/  325904 max/curr
symtab  :  3145728 mmap'd,  2020528/ 1949288 max/curr
client  :  1048576 mmap'd,     2088/    2080 max/curr
demangle:        0 mmap'd,        0/       0 max/curr
exectxt :        0 mmap'd,        0/       0 max/curr
errors  :        0 mmap'd,        0/       0 max/curr
ttaux   :    65536 mmap'd,     4752/    4624 max/curr

