Massif: alloc-fns:
Massif:   1: calloc
Massif:   2: realloc
Massif:   3: memalign
Massif:   4: __builtin_new
Massif:   5: __builtin_vec_new
Massif:   6: operator new(unsigned)
Massif:   7: operator new[](unsigned)
Massif:   8: operator new(unsigned long)
Massif:   9: operator new[](unsigned long)
Massif:   10: malloc
Massif:   11: operator new(unsigned, std::nothrow_t const&)
Massif:   12: operator new[](unsigned, std::nothrow_t const&)
Massif:   13: operator new(unsigned long, std::nothrow_t const&)
Massif:   14: operator new[](unsigned long, std::nothrow_t const&)
Massif: startup S.  0 (t:0, hp:0, ad:0, st:0)
Massif:   alloc S.  1 (t:100, hp:100, ad:0, st:0)
Massif: realloc S.  2 (t:100, hp:100, ad:0, st:0)
Massif: re-PEAK Sp  3 (t:100, hp:100, ad:0, st:0)
Massif: realloc S.  4 (t:150, hp:50, ad:0, st:0)
Massif: realloc S.  5 (t:250, hp:150, ad:0, st:0)
Massif: de-PEAK Sp  6 (t:250, hp:150, ad:0, st:0)
Massif: dealloc S.  7 (t:400, hp:0, ad:0, st:0)
Massif: heap allocs:          1
Massif: heap zero allocs:     0 (0%)
Massif: heap reallocs:        3
Massif: heap frees:           1
Massif: stack allocs:         0
Massif: stack frees:          0
Massif: XPts:                 5
Massif: top-XPts:             4 (80%)
Massif: dup'd XPts:           8
Massif: dup'd/freed XPts:     0
Massif: XPt-init-expansions:  1
Massif: XPt-later-expansions: 0
Massif: skipped snapshots:    0
Massif: real snapshots:       8
Massif: detailed snapshots:   2
Massif: peak snapshots:       2
Massif: cullings:             0
Massif: XCon_redos:           0
