Invalid read of size 8
   at 0x........: __strlen_sse2 (in /home/sewardj/VgTRUNK/ic111/memcheck/tests/x86/strlen-sse2-32)
   by 0x........: main (strlen-sse2-32.c:77)
 Address 0x........ is 8 bytes before a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (strlen-sse2-32.c:74)

Invalid read of size 8
   at 0x........: __strlen_sse2 (in /home/sewardj/VgTRUNK/ic111/memcheck/tests/x86/strlen-sse2-32)
   by 0x........: main (strlen-sse2-32.c:84)
 Address 0x........ is 8 bytes inside a block of size 12 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (strlen-sse2-32.c:80)

